# Generated by Django 3.2.7 on 2021-11-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=15)),
                ('Age', models.CharField(max_length=2)),
                ('Designation', models.CharField(max_length=15)),
                ('Role', models.CharField(max_length=15)),
                ('EmployeeNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Project_ID', models.CharField(max_length=10)),
                ('Deadline', models.DateField()),
                ('No_of_Members', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='my_user',
        ),
        migrations.CreateModel(
            name='appraisal',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('appr_no', models.CharField(max_length=6)),
                ('appr_text', models.CharField(max_length=300)),
                ('appr_pts', models.CharField(max_length=2)),
                ('date_of_appr', models.DateField()),
                ('magr_id', models.CharField(max_length=15)),
            ],
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('remk_no', models.CharField(max_length=6)),
                ('remk_text', models.CharField(max_length=300)),
                ('date_of_remk', models.DateField()),
                ('magr_id', models.CharField(max_length=15)),
            ],
            bases=('users.myuser',),
        ),
    ]
