# Generated by Django 3.2.5 on 2021-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=15)),
                ('Age', models.CharField(max_length=2)),
                ('Designation', models.CharField(max_length=15)),
                ('Department', models.CharField(max_length=15)),
                ('EmployeeNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='my_user',
        ),
    ]
