# Generated by Django 3.2.5 on 2021-11-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211120_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Department',
            new_name='Role',
        ),
    ]
