# Generated by Django 3.2.5 on 2021-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_department_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Project_ID', models.CharField(max_length=10)),
                ('Deadline', models.DateField()),
                ('No_of_Members', models.CharField(max_length=3)),
            ],
        ),
    ]
