# Generated by Django 3.2.5 on 2021-11-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='appraisal',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('appr_no', models.CharField(max_length=6)),
                ('appr_text', models.CharField(max_length=300)),
                ('appr_pts', models.CharField(max_length=2)),
                ('date_of_appr', models.DateField()),
                ('magr_id', models.CharField(max_length=15)),
            ],
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('remk_no', models.CharField(max_length=6)),
                ('remk_text', models.CharField(max_length=300)),
                ('date_of_remk', models.DateField()),
                ('magr_id', models.CharField(max_length=15)),
            ],
            bases=('users.myuser',),
        ),
    ]
